# Generated by Django 4.0.4 on 2022-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('ns_subject', models.CharField(max_length=200)),
                ('predicate', models.CharField(max_length=200)),
                ('ns_predicate', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('ns_object', models.CharField(max_length=200)),
            ],
        ),
    ]
